# This is an awk script for extracting the character widths from 
# an .afm file, and writing a C++ file defining the charwidths object
# containing the widths.

BEGIN {
  RS = "\r?\n";
  count = 0;
  print "// -*- C++ -*- pdf_fonts.cpp";
  print "// Copyright (C) 2002 Martin Bright <martin@boojum.org.uk>";
  print "";
  print "// This program is free software; you can redistribute it and/or modify";
  print "// it under the terms of the GNU General Public License as published by";
  print "// the Free Software Foundation; either version 2 of the License, or";
  print "// (at your option) any later version.";
  print "";
  print "// This program is distributed in the hope that it will be useful,";
  print "// but WITHOUT ANY WARRANTY; without even the implied warranty of";
  print "// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the";
  print "// GNU General Public License for more details.";
  print "";
  print "// You should have received a copy of the GNU General Public License";
  print "// along with this program; if not, write to the Free Software";
  print "// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA";
  print "";
  print "// $Id$";
  print "";
  print "// This file was automatically generated by afm2cpp.awk";
  print "";
  print "#ifdef __GNUG__";
  print "#pragma implementation";
  print "#endif";
  print "";
  print "#include <ringing/pdf_fonts.h>";
  print "";
  print "RINGING_START_NAMESPACE";
  print "";
}

END {
  print "map<string, const int*> charwidths::widths;";
  print "";
  print "void charwidths::init()";
  print "{";
  for(i = 1; i <= count; ++i)
    print "  widths[\"" fonts[i] "\"] = widths_" i ";";
  print "}";
  print "";
  print "RINGING_END_NAMESPACE";
}

/FontName/ {
  fonts[++count] = $2;
  print "static const int widths_" count "[] = {";
}

/StartCharMetrics/ {
  for(i = 32; i < 255; ++i)
    widths[i] = 0;
}

/StartCharMetrics/, /EndCharMetrics/ {
  n = split($0, A, ";");
  c = 0; w = 0;
  for(i = 1; i <= n; ++i) {
    m = split(A[i], B, " ");
    if(m >= 2 && B[1] == "C") c = B[2];
    if(m >= 2 && B[1] == "WX") w = B[2];
  }
  if(c > 0) widths[c] = w;
}

/EndCharMetrics/ {
  for(i = 32; i < 254; ++i) {
    if(i % 14 == 4) printf "\n    ";
    printf "%d, ", widths[i];
  }
  print widths[254];
  print "};\n";
}
